# Generated by Django 5.2 on 2025-06-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['departamento__codigo', 'codigo'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterField(
            model_name='tributoresumen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('departamento', 'codigo')},
        ),
    ]
