# Generated by Django 5.2 on 2025-06-04 05:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0002_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='descActividad',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='nombreComercial',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='motivoContin',
            field=models.CharField(blank=True, help_text='Motivo de Contingencia', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='plazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dte.plazo', validators=[django.core.validators.RegexValidator(message='Plazo debe tener formato 01, 02 o 03', regex='^0[1-3]$')]),
        ),
    ]
