# Generated by Django 5.2 on 2025-06-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0004_alter_facturaelectronica_emisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='dte.receptor'),
        ),
    ]
