# Generated by Django 5.2 on 2025-06-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0002_factura_campos_hacienda'),
        ('dte', '0005_alter_facturaelectronica_receptor'),
    ]

    operations = [
    ]
