# Generated by Django 5.2 on 2025-07-12 22:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0006_merge_20250621_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='ivaPerci1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA Percibido'),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='nrc',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='NRC debe tener entre 2 y 8 dígitos.', regex='^[0-9]{1,8}$')]),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='numeroControl',
            field=models.CharField(help_text='Formato: DTE-01-XXXXXXXX-XXXXXXXXXXXXXXX o DTE-03-XXXXXXXX-XXXXXXXXXXXXXXX', max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nrc',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='NRC debe tener entre 1 y 8 dígitos.', regex='^\\d{1,8}$')]),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='totalIva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
