# Generated by Django 5.2 on 2025-07-21 16:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0007_resumen_ivaperci1_alter_emisor_nrc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='descu',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Descuento (solo FSE) - diferente de totalDescu', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='resumen',
            name='observaciones_fse',
            field=models.TextField(blank=True, help_text='Observaciones específicas para FSE', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='total_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de Compra (solo FSE)', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
