# Generated by Django 5.2 on 2025-07-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0008_resumen_descu_resumen_observaciones_fse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_nota_credito', models.TextField(help_text='Descripción del motivo por el cual se emite la nota de crédito', max_length=500, verbose_name='Motivo de la Nota de Crédito')),
                ('documento_origen_uuid', models.CharField(help_text='Código de generación del CCF o NC original que se está acreditando', max_length=36, verbose_name='UUID del Documento Original')),
                ('tipo_nota_credito', models.CharField(choices=[('TOTAL', 'Nota de Crédito Total'), ('PARCIAL', 'Nota de Crédito Parcial'), ('CORRECCION', 'Corrección de Datos'), ('DEVOLUCION', 'Devolución de Mercadería'), ('DESCUENTO', 'Descuento Posterior')], default='PARCIAL', max_length=20, verbose_name='Tipo de Nota de Crédito')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_detalle', to='dte.facturaelectronica')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Notas de Crédito',
                'db_table': 'dte_nota_credito_detalle',
            },
        ),
    ]
