# Generated by Django 5.2 on 2025-08-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0009_notacreditodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado_hacienda',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('ACEPTADO_CON_OBSERVACIONES', 'Aceptado con Observaciones'), ('RECHAZADO', 'Rechazado'), ('NO_ENVIADO', 'No Enviado')], default='NO_ENVIADO', help_text='Estado del documento en Hacienda', max_length=30),
        ),
    ]
