# Generated by Django 5.2 on 2025-08-02 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0010_alter_facturaelectronica_estado_hacienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnulacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_generacion', models.CharField(help_text='UUID para identificar esta anulación', max_length=36, unique=True, verbose_name='Código de Generación')),
                ('fecha_anulacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Anulación')),
                ('hora_anulacion', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Anulación')),
                ('tipo_anulacion', models.IntegerField(choices=[(1, 'Anulación con documento de reemplazo'), (2, 'Anulación sin documento de reemplazo'), (3, 'Corrección de datos')], default=2, verbose_name='Tipo de Anulación')),
                ('motivo_anulacion', models.TextField(help_text='Descripción del motivo de la anulación', max_length=250, verbose_name='Motivo de Anulación')),
                ('nombre_responsable', models.CharField(max_length=100, verbose_name='Nombre del Responsable')),
                ('tipo_doc_responsable', models.CharField(choices=[('36', 'NIT'), ('13', 'DUI'), ('02', 'Carnet de Residente'), ('03', 'Pasaporte'), ('37', 'Otro')], max_length=2, verbose_name='Tipo Documento Responsable')),
                ('num_doc_responsable', models.CharField(max_length=20, verbose_name='Número Documento Responsable')),
                ('nombre_solicita', models.CharField(max_length=100, verbose_name='Nombre quien Solicita')),
                ('tipo_doc_solicita', models.CharField(choices=[('36', 'NIT'), ('13', 'DUI'), ('02', 'Carnet de Residente'), ('03', 'Pasaporte'), ('37', 'Otro')], max_length=2, verbose_name='Tipo Documento Solicitante')),
                ('num_doc_solicita', models.CharField(max_length=20, verbose_name='Número Documento Solicitante')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado a Hacienda'), ('ACEPTADO', 'Aceptado por Hacienda'), ('RECHAZADO', 'Rechazado por Hacienda'), ('ERROR', 'Error en Procesamiento')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('sello_recepcion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Sello de Recepción')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('respuesta_hacienda', models.JSONField(blank=True, null=True, verbose_name='Respuesta Completa de Hacienda')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino', verbose_name='Ambiente')),
                ('documento_anular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anulaciones', to='dte.facturaelectronica', verbose_name='Documento a Anular')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.emisor', verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Anulación de Documento',
                'verbose_name_plural': 'Anulaciones de Documentos',
                'db_table': 'dte_anulacion_documento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
