# Generated by Django 5.2 on 2025-08-03 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0011_anulaciondocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_acreditada', models.DecimalField(decimal_places=2, help_text='Cantidad del item original que se acredita en esta NC', max_digits=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('item_nota_credito', models.ForeignKey(help_text='Item de la NC que referencia al original', on_delete=django.db.models.deletion.CASCADE, related_name='referencia_item_original', to='dte.cuerpodocumentoitem')),
                ('item_original', models.ForeignKey(help_text='Item del CCF original al que se aplica esta NC', on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito_aplicadas', to='dte.cuerpodocumentoitem')),
                ('nota_credito', models.ForeignKey(help_text='NC que contiene este item', on_delete=django.db.models.deletion.CASCADE, related_name='items_referenciados', to='dte.facturaelectronica')),
            ],
            options={
                'verbose_name': 'Item de Nota de Crédito',
                'verbose_name_plural': 'Items de Notas de Crédito',
                'db_table': 'dte_item_nota_credito',
                'indexes': [models.Index(fields=['item_original'], name='dte_item_no_item_or_c8ac91_idx'), models.Index(fields=['nota_credito'], name='dte_item_no_nota_cr_da9282_idx')],
                'constraints': [models.UniqueConstraint(fields=('item_original', 'item_nota_credito'), name='unique_item_original_nc')],
            },
        ),
    ]
