# Generated by Django 5.2 on 2025-08-04 05:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0012_agregar_control_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpodocumentoitem',
            name='descuentoAplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento porcentual aplicado al calcular el precio unitario', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
