# Generated by Django 5.2 on 2025-08-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0013_cuerpodocumentoitem_descuentoaplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpodocumentoitem',
            name='precioIndiceUsado',
            field=models.IntegerField(choices=[(1, 'Precio 1'), (2, 'Precio 2'), (3, 'Precio 3'), (4, 'Precio 4')], default=1, help_text='Índice del precio utilizado del producto (1-4)'),
        ),
    ]
