# Generated by Django 5.2 on 2025-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo1',
            field=models.CharField(default='PROD-1', max_length=25, unique=True, verbose_name='Código 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Código 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Código 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo4',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Código 4'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_por_defecto',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%')], default=0, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio1',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Precio 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio 3'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio 4'),
        ),
    ]
