# Generated by Django 5.2 on 2025-06-24 07:25

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_imagen1_alter_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.producto_image_path, validators=[productos.models.validate_image_size, productos.models.validate_image_format], verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.producto_image_path, validators=[productos.models.validate_image_size, productos.models.validate_image_format], verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.producto_image_path, validators=[productos.models.validate_image_size, productos.models.validate_image_format], verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.producto_image_path, validators=[productos.models.validate_image_size, productos.models.validate_image_format], verbose_name='Imagen 4'),
        ),
    ]
