# Generated by Django 5.2 on 2025-08-05 01:08

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_imagen1_alter_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False, help_text='Solo usuarios activos pueden acceder al sistema', verbose_name='Usuario Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=productos.models.get_default_rol, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.rol', verbose_name='Rol'),
        ),
    ]
